Article 116 of mod.sources:
Relay-Version: version B 2.10.2 9/18/84; site brl-smoke.ARPA
Path: brl-smoke!brl-adm!seismo!harvard!talcott!panda!sources-request
From: sources-request@panda.UUCP
Newsgroups: mod.sources
Subject: tvx: 1 of 10
Message-ID: <1482@panda.UUCP>
Date: 8 Mar 86 12:58:48 GMT
Date-Received: 9 Mar 86 05:38:30 GMT
Sender: jpn@panda.UUCP
Lines: 48
Approved: jpn@panda.UUCP

Mod.sources:  Volume 4, Issue 15
Submitted by: gatech!unmvax!wampler (Bruce Wampler)


#-------- TVX, part 1 of 10 ----------

	This is a new, improved version of TVX, including:

	- Bug fixes and added commands
	- vi emulation (95% compatible for 'basic' users, but no ex..)
	- New modeless version, including emacs emulation
	- Unix System V support
	- Improved documentation, including interactive tutorial
	- Improved Atari ST support
	- Improved configuration program

	If you can't easily download this code to IBM-PCs or Atari STs,
I will provide all source on IBM-PC compatible or Atari-ST disks.
(It requires 2 360K disks).  Please make it easy for me by pre-formatting
the disks and providing return postage.  (I will accept an extra
disk in leiu of postage if that is easier for you).

Please direct all comments, bug reports, suggestions, disk requests,
and new port information to me.

Dr. Bruce E. Wampler
University of New Mexico
Department of Computer Science
Albuquerque, NM 87131

..{ucbvax | seismo!gatech | ihnp4!lanl | pur-ee}!unmvax!wampler

----------------
Distribution table of contents:

1 of 10:	This file.  No actual shar files
2 of 10:	README, tvx.ref, vix.ref, emax.ref, tvx_tut.doc
3 of 10:	Makefile, Makefile.sysV, tvx_make.bat, atari.info,
		tvx_ibm.c, tvx_unix.c
4 of 10:	tvx_1.c, tvx_defs.ic
5 of 10:	tvx_2.c, tvx_term.ic
6 of 10:	tvx_edit.c, tvx_glbl.ic
7 of 10:	tvx_io.c, tvx_lib.c
8 of 10:	tvx_lex.c, tvx_cfg.c, tvx_ptch.c
9 of 10:	tvx_ref1.doc	(part 1 of doucment)
10 of 10:	tvx_ref2.doc	(part 2 of document)

#-------- END OF PART 1 of 10 --------


